# remember to export praw keys!
# TODO: export praw keys as a dependency
python_tests(
  name='tests',
  dependencies=[
    '3rdparty:hypothesis',
    '3rdparty:praw',
    'src/main/python/submission_moderator:lib',
  ],
)
