# remember to export praw keys!
# TODO: export praw keys as a dependency
python_tests(
  name='tests',
  dependencies=[
    '3rdparty/python:hypothesis',
    '3rdparty/python:praw',
    'src/main/python/submission_moderator:lib',
  ],
)
