language: python
jobs:
  include:
    - name: "Unit Test Submission Moderator"
      python: "3.7"
      env: TESTDIR=modules/submission-moderator
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install -r ${TESTDIR}/requirements.txt
install:
  - pip install ${TESTDIR}/.
script:
  - pytest -v
