# TODO: Find a way to shorten build time.
#   Unfortunately, travis cannot cache docker images. ¯\_(ツ)_/¯
#   Consider deploying image to dockerhub (only when it changes),
#   and pulling the image with each build.
#   https://stackoverflow.com/questions/35305492/cache-docker-images-on-travis-ci
#   https://docs.docker.com/registry/recipes/mirror/
#   https://github.com/travis-ci/travis-ci/issues/5358
# Reduce memory usage to avoid docker 137 (out-of-memory) errors
#   https://docs.bazel.build/versions/2.2.0/memory-saving-mode.html
# Docker Flags Explained
#   Keep the docker container running throughout the build.
#     --detach --interactive --tty
#   Keep memory usage in check
#     --memory=1g --memory-swap=10g --oom-kill-disable
language: python
python: "3.7"
env:
  global:
    - IMAGE_TAG=datascience-bot/dev
    - CONTAINER_NAME=my-container
    - IMAGE_WORKDIR=/workspaces/datascience-bot
    - DOCKER_RUN_FLAGS="--memory=1g --memory-swap=10g --oom-kill-disable --detach --interactive --tty --volume=$(pwd):${IMAGE_WORKDIR} --workdir=${IMAGE_WORKDIR}"
services:
  - docker
before_install:
  - docker build -t ${IMAGE_TAG} .
  - docker run ${DOCKER_RUN_FLAGS} --name=${CONTAINER_NAME} ${IMAGE_TAG}
before_script:
  - ls -a
script:
  - docker exec ${CONTAINER_NAME} /bin/bash -c ". travis-container-script.sh"
after_script:
  - ls -a
