# TODO: Find a way to shorten build time.
#   Unfortunately, travis cannot cache docker images. ¯\_(ツ)_/¯
#   Consider deploying image to dockerhub (only when it changes),
#   and pulling the image with each build.
# https://stackoverflow.com/questions/35305492/cache-docker-images-on-travis-ci
# https://docs.docker.com/registry/recipes/mirror/
# https://github.com/travis-ci/travis-ci/issues/5358
language: python
python: "3.7"
env:
  - IMAGE_TAG=tradingai/bazel IMAGE_WORKDIR=/workspaces/datascience-bot
services:
  - docker
before_install:
  - python --version
  - echo "DATASCIENCE_BOT_USERNAME=${DATASCIENCE_BOT_USERNAME}" >> ./.env
  - echo "DATASCIENCE_BOT_PASSWORD=${DATASCIENCE_BOT_PASSWORD}" >> ./.env
  - echo "DATASCIENCE_BOT_CLIENT_ID=${DATASCIENCE_BOT_CLIENT_ID}" >> ./.env
  - echo "DATASCIENCE_BOT_CLIENT_SECRET=${DATASCIENCE_BOT_CLIENT_SECRET}" >> ./.env
  - docker pull ${IMAGE_TAG}
  # - docker build -t ${IMAGE_TAG} .
  - docker run -d -p 127.0.0.1:80:4567 --env-file=./.env --volume=${pwd}:${IMAGE_WORKDIR} ${IMAGE_TAG} /bin/bash -c "cd ${IMAGE_WORKDIR}; bazel version"
  - docker ps -a
script:
  - docker run ${IMAGE_TAG} /bin/bash -c "bazel build //..."
  - docker run ${IMAGE_TAG} /bin/bash -c "bazel test //..."
