# TODO: Find a way to shorten build time.
#   Unfortunately, travis cannot cache docker images. ¯\_(ツ)_/¯
#   Consider deploying image to dockerhub (only when it changes),
#   and pulling the image with each build.
# https://stackoverflow.com/questions/35305492/cache-docker-images-on-travis-ci
# https://docs.docker.com/registry/recipes/mirror/
# https://github.com/travis-ci/travis-ci/issues/5358
language: python
python: "3.7"
services:
  - docker
before_install:
  - python --version
  - echo "DATASCIENCE_BOT_USERNAME=${DATASCIENCE_BOT_USERNAME}" >> ./.env
  - echo "DATASCIENCE_BOT_PASSWORD=${DATASCIENCE_BOT_PASSWORD}" >> ./.env
  - echo "DATASCIENCE_BOT_CLIENT_ID=${DATASCIENCE_BOT_CLIENT_ID}" >> ./.env
  - echo "DATASCIENCE_BOT_CLIENT_SECRET=${DATASCIENCE_BOT_CLIENT_SECRET}" >> ./.env
  - docker build -t datascience-bot/bazel .
  - docker run -d -p 127.0.0.1:80:4567 --env-file=./.env --volume=$(pwd):/workspaces/datascience-bot datascience-bot/bazel /bin/bash -c "cd /workspaces/datascience-bot/; bazel version"
  - docker ps -a
script:
  - docker run datascience-bot/bazel /bin/bash -c "bazel build //..."
  - docker run datascience-bot/bazel /bin/bash -c "bazel test //..."
