[GLOBAL]
pants_version = "1.25.0"

# use python3 for the whole repo
[python-setup]
interpreter_constraints = ["CPython>=3.6"]

[cache]
read_from = ["/tmp/pants"]
read = true
write_to = ["/tmp/pants"]
write = true

[pytest]
version = "pytest>=5.3.5"

[test.junit]
chroot = true  # optional `false` deprecated; removal in 1.29
fast = false  # optional `true` deprecated; removal in 1.27

[test.pytest]
chroot = true  # optional `false` deprecated; removal in 1.29
fast = false  # optional `true` deprecated; removal in 1.27

[resolver]
resolver = "coursier"
