# -*- coding: utf-8 -*-
# --- BEGIN AUTOGENERATED SECTION --------------------------------------------
# This preamble has been system generated and should not be altered
import sys

# formatted by zipper._gen_path_loader
extra_paths = {}

for path in extra_paths:
    sys.path.append(path)
# --- END AUTOGENERATED SECTION ----------------------------------------------
